### ISSUE TITLE
cs.yml is buggy

### ISSUE THREAD

**Issue by cforce** [two-pack/redmine_xls_export#33]
ActionView::Template::Error (...plugins/redmine_xls_export/config/locales/cs.yml): mapping values are not allowed in this context at line 2 column 3):
    16:   <p><%= f.text_field :firstname, :required => true %></p>
    17:   <p><%= f.text_field :lastname, :required => true %></p>
    18:   <p><%= f.text_field :mail, :required => true %></p>
    19:   <p><%= f.select :language, lang_options_for_select %></p>
    20:   <% if Setting.openid? %>
    21:   <p><%= f.text_field :identity_url  %></p>
    22:   <% end %>
  lib/redmine/i18n.rb:152:in `init_translations'
  lib/redmine/i18n.rb:166:in`lookup'
  lib/redmine/i18n.rb:52:in `ll'
  lib/redmine/i18n.rb:96:in`block (2 levels) in languages_options'
  lib/redmine/i18n.rb:96:in `map'
  lib/redmine/i18n.rb:96:in`block in languages_options'
  lib/redmine/i18n.rb:95:in `languages_options'
  app/helpers/application_helper.rb:933:in`lang_options_for_select'
  app/views/my/account.html.erb:19:in `block in _app_views_my_account_html_erb___548644357_111959040'
  app/helpers/application_helper.rb:948:in`labelled_form_for'
  app/views/my/account.html.erb:9:in `_app_views_my_account_html_erb___548644357_111959040'

**Comment by picman** [comment]
Can you try this (in config/locales):

$ irb -ryaml
irb(main):001:0> YAML.load_file 'cs.yml'

Everything is correct on my PC. Can you also append you Rails/Redmine versions.
I've changed the codding style according to the latest standard, so I used:

label_plugin_xlse_relations: Exportovat vazby

instead of:

label_plugin_xlse_relations: "Exportovat vazby"

So without needless apostrophes. Can you try to add apostrophes an re-test again, please?

**Comment by cforce** [comment]
No sorry, i already removed the file and now it works 
Using 

Environment:
  Redmine version                2.3.2.stable
  Ruby version                   2.0.0-p0 (2013-02-24) [i686-linux]
  Rails version                  3.2.13
  Environment                    production
  Database adapter               Mysql2
